version: 2.1

orbs:
  vr: kohirens/version-release@4.4.4

parameters:
  secrets:
    default: kohirens-automation
    description: Secrets context
    type: string
  secrets_docker:
    default: kohirens-docker-automation
    description: Secrets context
    type: string
  secrets_iac_test:
    default: kohirens-iac-test
    description: Secrets context
    type: string
  ssh_finger:
    default: "SHA256:yfSgz131DaRnkrMhsbLYExmhp2xIMr8UJH3daAC4dC8"
    description: SSH fingerprint.
    type: string
  triggered_flow:
    default: "workflow-selector"
    description: Workflow to be executed.
    type: string

jobs:
  run-test:
    docker:
      - image: hashicorp/terraform:1.7.0
        auth:
          username: ${DH_USER}
          password: ${DH_PASS}
    steps:
      - checkout
      - run:
          command: terraform fmt -check -write=false -diff
      - run:
          command: |
            terraform init
            terraform validate
            terraform test

workflows:
  quality_checks:
    jobs:
      - run-test:
          context:
            - << pipeline.parameters.secrets_docker >>
            - << pipeline.parameters.secrets_iac_test >>
          filters: { branches: { ignore: /main|auto-update-changelog/ } }

  workflow-selector:
    when:
      and:
        - equal: ["workflow-selector", << pipeline.parameters.triggered_flow >>]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - vr/workflow-selector:
          context: << pipeline.parameters.secrets >>
          ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-changelog:
    when:
      and:
        - equal: ["publish-changelog", << pipeline.parameters.triggered_flow >>]
    jobs:
      - vr/publish-changelog:
          context: << pipeline.parameters.secrets >>
          ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-release-tag:
    when:
      and:
        - equal: ["publish-release-tag", << pipeline.parameters.triggered_flow >>]
    jobs:
      - vr/tag-and-release:
          context: << pipeline.parameters.secrets >>
